server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: 1asd
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      #ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
